judge:
  rsync: maycamp@arena.maycamp.com:/home/maycamp/arena.maycamp.com/shared/sets
valo:
  rsync: mcvalo@maycamp.com:/home/maycamp/arena.maycamp.com/shared/sets
grader:
  rsync: valo@localhost:/home/valo/spoj0/sets
maycamparena:
  rsync: contest@localhost:/home/contest/sets
ubuntu-VirtualBox:
  rsync: mcvalo@maycamp.com:/home/maycamp/arena.maycamp.com/shared/sets
vagrant-ubuntu-trusty-64:
  rsync: maycamp@arena.maycamp.com:/home/maycamp/arena.maycamp.com/shared/sets
ubuntu:
  rsync: maycamp@arena.maycamp.com:/home/maycamp/arena.maycamp.com/shared/sets
