---
- hosts: all
  sudo: no
  vars:
    - mysql_memory: 128M

  tasks:
    - name: Install packages
      action: apt pkg={{ item }} state=present
      sudo: yes
      with_items:
        - nodejs
        - libmysqlclient-dev
        - memcached
        - docker.io

    - name: enable memcached service
      sudo: yes
      action: service name=memcached state=started enabled=yes 

    - name: Add the user to the docker group
      user: name=vagrant groups=docker
      sudo: yes

    - name: install rvm
      shell: \curl -L https://get.rvm.io | bash -s stable --autolibs=3 creates=~/.rvm

    - name: install ruby
      shell: ~/.rvm/bin/rvm install --default 2.1.5 creates=~/.rvm/rubies/2.1.5

    - name: bundle install
      shell: 'executable=/bin/bash chdir=/vagrant . "$HOME/.rvm/scripts/rvm" && rvm use --default 2.1.5 && bundle'
